## [EssenceModularActor]
## Framework base class responsible for modular appearance management,
## safe pose control, and garment synchronization using immutable IDs.
class_name EssenceModularActor
extends EssenceActor

@export_category("Base Modular Configuration")
## The initial active full pose.
@export var current_pose_id: int = 1

## Visual registry indexed by integers (Pose ID -> Visual Group Node)
var poses_registry: Dictionary = {}

## Master list storing the integers representing the clothing the character is wearing (Save State).
var _equipped_items: Array[int] = []


func _ready() -> void:
	super._ready()
	_sync_modular_initial_state()

## Validates at design time or runtime whether the developer forgot to connect the pose.
func _validate_poses_registry() -> void:
	if poses_registry.is_empty():
		push_warning("[%s] ⚠️ WARNING: 'poses_registry' is EMPTY in the Inspector. The character will not be able to update their clothing or change their pose." % name)
		

func _sync_modular_initial_state() -> void:
	_equipped_items.clear()
	
	for pose_id in poses_registry.keys():
		var pose_node = poses_registry[pose_id]
		if is_instance_valid(pose_node):
			pose_node.visible = (int(pose_id) == current_pose_id)
			
	var active_pose = poses_registry.get(current_pose_id)
	if active_pose:
		# 1. Bake local inventory by forcing primitive integers
		for item_id in active_pose.registry.keys():
			if active_pose.registry[item_id].visible:
				_equipped_items.append(int(item_id))
				
		# 2. Bake shared inventory, forcing primitive integers
		if "shared_clothing_group" in active_pose and is_instance_valid(active_pose.shared_clothing_group):
			var shared = active_pose.shared_clothing_group
			for item_id in shared.registry.keys():
				if shared.registry[item_id].visible and not int(item_id) in _equipped_items:
					_equipped_items.append(int(item_id))
					
		# C,RITICAL FIX!: Force the first visual sync on startup
		# This overwrites any manual state left visible in the editor.
		active_pose.sync_equipped_items(_equipped_items)
		if "shared_clothing_group" in active_pose and is_instance_valid(active_pose.shared_clothing_group):
			active_pose.shared_clothing_group.sync_equipped_items(_equipped_items)

## PUBLIC API: Changes the posture using pure numeric identifiers.
func change_pose(target_pose_id: int) -> void:
	var target_id: int = int(target_pose_id)
	if not poses_registry.has(target_id) or target_id == current_pose_id:
		return
		
	var old_pose = poses_registry.get(current_pose_id)
	var new_pose = poses_registry.get(target_id)
	
	var old_shared = old_pose.shared_clothing_group if (old_pose and "shared_clothing_group" in old_pose) else null
	var new_shared = new_pose.shared_clothing_group if (new_pose and "shared_clothing_group" in new_pose) else null
	
	if old_pose: old_pose.visible = false
	if new_pose: new_pose.visible = true
	
	if old_shared and old_shared != new_shared: old_shared.visible = false
	if new_shared: new_shared.visible = true
	
	current_pose_id = target_id
	
	if new_pose:
		new_pose.hide_all_registered()
		new_pose.sync_equipped_items(_equipped_items)
	if new_shared:
		new_shared.hide_all_registered()
		new_shared.sync_equipped_items(_equipped_items)

## PUBLIC API: Modifies the status of an item in the logical inventory.
func modify_clothing(item_id: int, is_equipped: bool) -> void:
	var target_id: int = int(item_id)
	
	if is_equipped and not target_id in _equipped_items:
		_equipped_items.append(target_id)
	elif not is_equipped and target_id in _equipped_items:
		_equipped_items.erase(target_id)
		
	var active_pose = poses_registry.get(current_pose_id)
	if active_pose:
		active_pose.sync_equipped_items(_equipped_items)
		if "shared_clothing_group" in active_pose and is_instance_valid(active_pose.shared_clothing_group):
			active_pose.shared_clothing_group.sync_equipped_items(_equipped_items)
	else:
		push_warning("[%s] ⚠️ WARNING: Pose ID %d not found in 'poses_registry'. Check the Inspector." % [name, current_pose_id])
					

# ==========================================
# STATE SERIALIZATION (SAVE & LOAD)
# ==========================================

## PUBLIC API: Serializes the current state of the wardrobe and pose.
## Returns a clean dictionary containing only stable numeric IDs.
func get_clothing_state() -> Dictionary:
	return {
		"equipped_ids": _equipped_items.duplicate(),
		"current_pose": current_pose_id
	}


## PUBLIC API: Restores the pose and equipped items from the save file.
## Automatically sanitizes float numbers generated by Godot's native JSON format.
func apply_clothing_state(state: Dictionary) -> void:
	if state.has("equipped_ids"):
		_equipped_items.clear()
		for id in state["equipped_ids"]:
			_equipped_items.append(int(id)) # JSON Floating-Point Cleanup
			
	if state.has("current_pose"):
		var target_pose_id: int = int(state["current_pose"])
		if target_pose_id == current_pose_id:
			var active_pose = poses_registry.get(current_pose_id)
			if active_pose:
				active_pose.hide_all_registered()
				active_pose.sync_equipped_items(_equipped_items)
				if "shared_clothing_group" in active_pose and is_instance_valid(active_pose.shared_clothing_group):
					active_pose.shared_clothing_group.sync_equipped_items(_equipped_items)
		else:
			change_pose(target_pose_id)
